name: build-website
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
           python-version: 3.6
      - name: Generate html files from *.jemdoc
        shell: bash -l {0} 
        run: |
            chmod +x jemdoc.py
            for i in $(ls *.jemdoc); do ./jemdoc.py "$i"; done
            mkdir _build
            mv *.html _build
            
      - name: Deploying article on github pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _build
          CLEAN: true
          